function exportMarkdown(result) {
  const lines = [];
  lines.push(`# GEO Audit Report: ${result.url}`);
  lines.push(`**Date:** ${new Date(result.timestamp).toLocaleDateString()}`);
  lines.push(`**Score:** ${result.score}/100 — ${result.level}`);
  lines.push('');
  lines.push('## Dimensions');
  for (const [key, dim] of Object.entries(result.dimensions)) {
    const pct = typeof dim.percentage !== 'undefined' ? `${dim.percentage}%` : `${dim.score}/${dim.maxScore}`;
    lines.push(`- **${key}**: ${pct} (${dim.passed}/${dim.total} checks passed)`);
    for (const check of dim.checks || []) {
      lines.push(`  - [${check.passed ? 'x' : ' '}] ${check.label}`);
    }
  }
  if (result.negativeSignals?.deductions?.length) {
    lines.push('');
    lines.push('## Negative Signals');
    for (const d of result.negativeSignals.deductions) {
      lines.push(`- ⚠ ${d.label} (-${d.deduction} pts)`);
    }
  }
  lines.push('');
  lines.push('## Recommendations');
  for (const rec of result.recommendations || []) {
    lines.push(`- [${rec.priority}] ${rec.issue}`);
    lines.push(`  → ${rec.fix}`);
  }
  return lines.join('\n');
}

function exportJson(result) {
  return JSON.stringify(result, null, 2);
}

function exportCsv(result) {
  const lines = ['Dimension,Score,MaxScore,Passed,Total'];
  for (const [key, dim] of Object.entries(result.dimensions)) {
    lines.push(`${key},${dim.score},${dim.maxScore},${dim.passed},${dim.total}`);
  }
  return lines.join('\n');
}

function exportHtml(result) {
  const dimHtml = Object.entries(result.dimensions).map(([k, d]) => {
    return `<tr><td>${k}</td><td>${d.percentage || 0}%</td><td>${d.passed || 0}/${d.total || d.checks || 0}</td></tr>`;
  }).join('');
  return '<!DOCTYPE html><html><head><meta charset="utf-8"><title>GEO Report: ' + result.url + '</title><style>body{font-family:system-ui,sans-serif;max-width:800px;margin:40px auto;padding:0 20px;background:#0f172a;color:#e2e8f0}h1{background:linear-gradient(135deg,#22c55e,#3b82f6);-webkit-background-clip:text;-webkit-text-fill-color:transparent}.score{font-size:64px;font-weight:800;text-align:center}.lvl{display:inline-block;padding:4px 12px;border-radius:999px;font-size:12px;font-weight:700;color:#fff}table{width:100%;border-collapse:collapse;margin:20px 0}td,th{padding:8px 12px;text-align:left;border-bottom:1px solid rgba(148,163,184,0.15)}.rec{border-left:3px solid #3b82f6;padding:8px 16px;margin:8px 0;background:rgba(255,255,255,0.03)}</style></head><body>' +
    '<h1>GEO Audit Report</h1>' +
    '<p style="color:#94a3b8">' + result.url + ' &middot; ' + new Date(result.timestamp).toLocaleDateString() + '</p>' +
    '<div class="score">' + result.score + '<span style="font-size:18px;color:#94a3b8">/100</span></div>' +
    '<div style="text-align:center;margin:10px 0"><span class="lvl" style="background:' + (result.level === "Excellent" ? "#22c55e" : result.level === "Good" ? "#3b82f6" : result.level === "Basic" ? "#eab308" : "#ef4444") + '">' + result.level + '</span></div>' +
    '<p style="color:#94a3b8;text-align:center">' + (result.summary || "") + '</p>' +
    '<h2>Dimensions</h2><table><thead><tr style="color:#94a3b8"><th>Dimension</th><th>Score</th><th>Checks</th></tr></thead><tbody>' + dimHtml + '</tbody></table>' +
    '<h2>Recommendations</h2>' + (result.recommendations || []).slice(0, 10).map(function(rec) {
      return '<div class="rec"><strong>' + rec.issue + '</strong><br/><span style="color:#94a3b8;font-size:14px">' + rec.fix + '</span><br/><span style="color:#64748b;font-size:12px">' + rec.dimension + ' &middot; ' + rec.priority + '</span></div>';
    }).join('') +
    '<p style="color:#64748b;font-size:12px;text-align:center;margin-top:40px">Generated by GeoScore &middot; geoscore.help</p>' +
    '</body></html>';
}

export { exportMarkdown, exportJson, exportCsv, exportHtml };
