/**
 * Minimal zero-dependency PDF writer (PDF 1.4, single page, ASCII).
 * Used by the Pro report download endpoint. Non-ASCII chars are
 * replaced with '?' (v1: English reports only).
 */
function escapePdfText(str) {
  var out = '';
  var s = String(str == null ? '' : str);
  for (var i = 0; i < s.length; i++) {
    var code = s.charCodeAt(i);
    if (code > 127) { out += '?'; continue; }
    if (code === 10) { out += ' '; continue; }
    if (code === 13) { continue; }
    if (code === 40 || code === 41 || code === 92) { out += '\\' + s[i]; continue; }
    out += s[i];
  }
  return out;
}

function textWidth(str, size) {
  // Approximate Helvetica average glyph width (~0.5em)
  return String(str).length * size * 0.5;
}

function buildPdfStream(audit) {
  var W = 612, H = 792;
  var margin = 50;
  var ops = [];
  var y = H - 56;
  var F = 'F1', FB = 'F2';

  function putText(str, size, font, x) {
    ops.push('BT /' + font + ' ' + size + ' Tf ' + x.toFixed(1) + ' ' + y.toFixed(1) + ' Td (' + escapePdfText(str) + ') Tj ET');
  }
  function putTextRight(str, size, font, rightX) {
    putText(str, size, font, rightX - textWidth(str, size));
  }
  function rule(x1, x2) {
    ops.push(x1 + ' ' + y.toFixed(1) + ' m ' + x2 + ' ' + y.toFixed(1) + ' l S');
  }

  // Header
  putText('GEO Audit Report', 18, FB, margin);
  y -= 20;
  putText(audit.url || '', 10, F, margin);
  y -= 14;
  putText('Date: ' + (audit.created_at || audit.timestamp || ''), 9, F, margin);
  y -= 22;
  putText('Score: ' + (audit.score == null ? '-' : audit.score) + '/100  (' + (audit.level || 'N/A') + ')', 16, FB, margin);
  y -= 18;
  if (audit.summary) {
    putText(audit.summary, 9, F, margin);
    y -= 13;
  }
  y -= 6;
  rule(margin, W - margin);
  y -= 16;

  // Dimensions table
  putText('Dimensions', 13, FB, margin);
  y -= 14;
  putText('Dimension', 10, FB, margin);
  putTextRight('Score', 10, FB, W - margin);
  putTextRight('Checks', 10, FB, W - margin - 70);
  y -= 10;
  rule(margin, W - margin);
  y -= 14;

  var dims = {};
  try { dims = (audit.dimensions && typeof audit.dimensions === 'string') ? JSON.parse(audit.dimensions) : (audit.dimensions || {}); } catch (e) { dims = {}; }
  Object.keys(dims).forEach(function (key) {
    if (y < 50) return;
    var d = dims[key] || {};
    var pct = typeof d.percentage !== 'undefined' ? d.percentage : 0;
    var passed = d.passed || 0;
    var total = d.total || d.checks || 0;
    putText(key, 9, F, margin);
    putTextRight(String(pct) + '%', 9, F, W - margin - 70);
    putTextRight(passed + '/' + total, 9, F, W - margin);
    y -= 13;
  });
  y -= 8;
  rule(margin, W - margin);
  y -= 16;

  // Recommendations
  putText('Top Recommendations', 13, FB, margin);
  y -= 14;
  var recs = [];
  try { recs = (audit.recommendations && typeof audit.recommendations === 'string') ? JSON.parse(audit.recommendations) : (audit.recommendations || []); } catch (e) { recs = []; }
  recs.slice(0, 10).forEach(function (rec, i) {
    if (y < 40) return;
    putText((i + 1) + '. ' + (rec.issue || 'Issue'), 9, FB, margin);
    y -= 12;
    if (rec.fix && y > 40) {
      putText(rec.fix, 9, F, margin + 10);
      y -= 12;
    }
  });

  // Footer
  y = H - 30;
  putText('Generated by GeoScore - geoscore.help', 8, F, margin);

  return ops.join('\n') + '\n';
}

export function renderAuditPdf(audit) {
  var stream = buildPdfStream(audit);
  var encoder = new TextEncoder();
  var streamBytes = encoder.encode(stream);

  var objects = [];
  objects.push('<< /Type /Catalog /Pages 2 0 R >>');
  objects.push('<< /Type /Pages /Kids [3 0 R] /Count 1 >>');
  objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
  objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');
  objects.push('<< /Length ' + streamBytes.length + ' >>\nstream\n' + stream + 'endstream');

  var parts = ['%PDF-1.4\n%\xe2\xe3\xcf\xd3\n'];
  var offsets = [0];
  objects.forEach(function (obj, i) {
    offsets.push(parts.join('').length);
    parts.push((i + 1) + ' 0 obj\n' + obj + '\nendobj\n');
  });

  var xrefStart = parts.join('').length;
  var xref = 'xref\n0 ' + (objects.length + 1) + '\n';
  xref += '0000000000 65535 f \n';
  offsets.slice(1).forEach(function (off) {
    xref += String(off).padStart(10, '0') + ' 00000 n \n';
  });
  xref += 'trailer\n<< /Size ' + (objects.length + 1) + ' /Root 1 0 R >>\nstartxref\n' + xrefStart + '\n%%EOF\n';

  parts.push(xref);
  return encoder.encode(parts.join(''));
}
